### ISSUE TITLE
clean up csca.R

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#119]
- phytools dependency is real?
- remove remnant codes like this.
https://github.com/kfuku52/amalgkit/blob/72b2009d9e0a437244b755b1e2e0749a2d64ec87/amalgkit/csca.R#L530-L531

**Comment by kfuku52** [comment]
@Hego-CCTB Have you ever got csca to work properly? The current code even depends on the species tree, which should be totally unnecessary..

**Comment by kfuku52** [comment]
@Hego-CCTB Could you provide an example of `multisp_pca_maxGenePerOG*.pdf` ?

**Comment by Hego-CCTB** [comment]
I haven't touched csca since the initial integration into amalgkit, which was done here:
https://github.com/kfuku52/amalgkit/issues/13

In that issue I posted my csca output, which is this file:
[csca.zip](https://github.com/kfuku52/amalgkit/files/11137190/csca.zip)

That one contains 2 `multisp_pca_maxGenePerOG*.pdf ` files

**Comment by kfuku52** [comment]
Thanks! The problems have been solved in my recent commits.
