### ISSUE TITLE
amalgkit curate --h

### ISSUE THREAD

**Issue by docxology** [kfuku52/amalgkit#142]
```
  --batch_effect_alg (no|sva|ruvseq|combatseq)
                        default=sva: batch-effect removal algorithm. no: no batch-effect removal. sva: surrogate variable analysis. Use with log-transformed
                        values. ruvseq: batch effect removal based on control genes. Control genes are obtained from the residuals of a GLM. If log-fpkm/tpm
                        is set, transformation will be applied after batch-effect removal. combatseq: batch effect removal based on known batch effects
                        (bioproject). If log-fpkm/tpm is set, transformation will be applied after batch-effect removal.

```

The sentence "If log-fpkm/tpm is set, transformation will be applied after batch-effect removal." is repeated twice. 

Also I feel that this information could be useful in the Wiki for curate https://github.com/kfuku52/amalgkit/wiki/amalgkit-curate because some of these flags are not present there.

**Comment by kfuku52** [comment]
Thank you for bringing this to our attention! The repetition occurred because the information is relevant to both ruvseq and combatseq. We are currently in the process of refining the functions within curate. Once we conclude the active development phase, we will ensure that the Wiki is updated accordingly. For now, I updated the help messages.

https://github.com/kfuku52/amalgkit/commit/971642d13821780b8d2b599e55f2aba048ab5fe3
