### ISSUE TITLE
Introduce a natural language processing for metadata curation

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#2]
Currently `metadata` command relies on the huge keyword library in the `.config` files. This could be largely replaced/automatically-generated by a natural language processing technique. Even if we successfully replaced it, the `.config` files shouldn't be completely abandoned because it provides a platform of manual tweaking by users.

**Comment by kfuku52** [comment]
@Hego-CCTB Could you post a summary of what you've implemented for this and its limitation we've discussed?

**Comment by Hego-CCTB** [comment]
I haven't touched the NLP project in a while, after hitting a major roadblock. I'll make a summary.

**Comment by kfuku52** [comment]
Thanks. We need a summary to record how we ended up with handling this problem, to close the issue.

**Comment by Hego-CCTB** [comment]
The current NLP algorithm is performing fairly sloppy and suffers mainly from one big issue: lack of context. The NLP framework used was originally made for analysis of full sentences, making it easier for the algorithm to distinguish between word categories/classes and implied meaning. Since the descriptions in our Metadata are often sparse, the current implementation has trouble identifying the important parts of the descriptions. Meaning, the NLP algorithm performs OK with singular words, but struggles as soon as the description gets more complicated or includes info not relevant to the category (like including treatment in the tissue column, something like 'leaves drought'). 

I believe fixing this is fundamentally possible, either for the current NLP algorithm, or by trying a different approach (classification by supervised machine learning). However, doing so would be immensely time consuming and ultimately not worth it, given there are more pressing matters at hand that need implemention. 

I'll probably play with this a bit more in my own free time, since I'm interested in the topic, but work hours are better spend solving metadata curation by using config files.
