### ISSUE TITLE
free keyword config

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#39]
Currently the config files lack the one for free keywords (i.e., keywords that are not associated with a particular Entrez search field), but `search_term_tissue.config` can be used as is, so why don't we rename it as `search_term_keyword.config`?

**Comment by Hego-CCTB** [comment]
makes sense, esp. since a user might look for whole organs, conditions mutants etc. rather than tissue. 

Renaming everything, the entrez search command now looks like this:
`Entrez search term: "Aquilegia coerulea"[Organism] AND (root OR flower OR leaf OR drought stress) AND [...]`

I also renamed all relevant instances for "tissue" to "keyword".

**Comment by kfuku52** [comment]
Thank you. Sounds good!

**Comment by kfuku52** [comment]
It would be nice if you could tag the commit when it's done. https://github.com/kfuku52/amalgkit/commit/73ce56fd3aa28536774b86e6453122c1564e56de

**Comment by kfuku52** [comment]
search_term_keyword.config is missing.
https://github.com/kfuku52/amalgkit/tree/master/config/test

https://github.com/kfuku52/amalgkit/tree/master/config/viridiplantae_test

**Comment by Hego-CCTB** [comment]
Ah, they slipped past the commit as unversioned files. Updated in:
https://github.com/kfuku52/amalgkit/commit/a5783a4f4e9824be6f2e16bb8268d0d979d0bcc1
