### ISSUE TITLE
--batch base

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#51]
Currently, --batch takes zero-based index, so, on SGE for example, array jobs should be submitted like `--batch $[${SGE_TASK_ID}-1]`. I'm thinking if it would be better if the index starts from one, not zero. The one-based index is also easy to locate data when browsing the metadata table with Excel. @Hego-CCTB If there is no issue, I'd like to change it.

**Comment by Hego-CCTB** [comment]
sure! no problem w/ me

**Comment by kfuku52** [comment]
Applied the change to `getfastq` and `quant` in https://github.com/kfuku52/amalgkit/commit/62ac91b798af63055cee842bbb3e44bc4f8d8cd8

@Hego-CCTB Could you take care of --batch in `curate`? Currently --batch values do not appear to be used at all except for a few check with `is not None`. As we discussed previously, `curate` should choose species and detect all necessary input automatically according to --batch.

**Comment by Hego-CCTB** [comment]
sure, can do!

**Comment by kfuku52** [comment]
related bug fix https://github.com/kfuku52/amalgkit/commit/eeac07694a5d6ad775cb20617e06c40e3d6bf89d

**Comment by kfuku52** [comment]
@Hego-CCTB bump

**Comment by Hego-CCTB** [comment]
I will take care of this soon. I have tons of data lined up for `amalgkit curate` which I'd like to run `--batch` on.

**Comment by Hego-CCTB** [comment]
Added this here, but never made the closing report:
https://github.com/kfuku52/amalgkit/commit/b397f1a9b9661d9cedf53a0bc201acc44a73df85

`amalgkit curate --batch` works similar to other batch commands for amalgkit, just on species basis, rather than sample basis. i.e. if you have 3 species in your metadata, `amalgkit curate --batch 2` will try to process the 2nd species in the metadata sheet (in order of first occurrence).
